# Generated by Django 5.2.5 on 2025-08-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_student_user_registrar"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_img",
            field=models.ImageField(
                default="users/profile_imgs/default.png",
                upload_to="users/profile_imgs/",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="profile_img",
            field=models.ImageField(
                default="users/profile_imgs/default.png",
                upload_to="users/profile_imgs/",
            ),
        ),
    ]
