# Generated by Django 5.2.5 on 2025-08-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_student_user_alter_teacher_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrar",
            name="profile_img",
            field=models.ImageField(
                default="users/profile_imgs/default.png",
                upload_to="users/profile_imgs/",
            ),
        ),
    ]
