# Generated by Django 5.2.5 on 2025-08-30 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculums", "0001_initial"),
        ("users", "0006_alter_registrar_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="program",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="curriculums.program",
            ),
        ),
    ]
