# Generated by Django 5.2.5 on 2025-08-30 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculums", "0001_initial"),
        ("users", "0007_student_program"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="curriculums.program",
            ),
        ),
    ]
