# Generated by Django 5.2.5 on 2025-08-19 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("credits", models.IntegerField()),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="departments.department",
                    ),
                ),
                (
                    "prerequisite_courses",
                    models.ManyToManyField(
                        blank=True, related_name="prerequisites", to="courses.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_number", models.IntegerField()),
                ("capacity", models.PositiveSmallIntegerField(default=0)),
                ("year", models.IntegerField()),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("spring", "Spring"),
                            ("fall", "Fall"),
                            ("summer", "Summer"),
                        ]
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="courses.course",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "unique_together": {("course", "section_number", "year", "semester")},
            },
        ),
    ]
