# Generated by Django 5.2.5 on 2025-08-19 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="users.teacher",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("course", "section_number", "year", "semester")},
        ),
    ]
