# Generated by Django 5.2.5 on 2025-08-20 10:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        ("users", "0002_alter_student_user_registrar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AA", "AA"),
                            ("AB", "AB"),
                            ("BB", "BB"),
                            ("BC", "BC"),
                            ("CC", "CC"),
                            ("CD", "CD"),
                            ("DD", "DD"),
                            ("FF", "FF"),
                            ("P", "Pending"),
                        ],
                        default="P",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.section",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "section")},
            },
        ),
        migrations.AddField(
            model_name="section",
            name="students",
            field=models.ManyToManyField(
                related_name="sections",
                through="courses.Enrollment",
                to="users.student",
            ),
        ),
    ]
