# Generated by Django 5.2.5 on 2025-08-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_enrollment_section_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_image",
            field=models.ImageField(blank=True, null=True, upload_to="course_images/"),
        ),
    ]
