# Generated by Django 5.2.5 on 2025-08-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_course_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="course_image",
            new_name="image",
        ),
    ]
