# Generated by Django 5.2.5 on 2025-08-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_rename_course_image_course_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="image",
        ),
        migrations.AddField(
            model_name="section",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="course_images/"),
        ),
    ]
