# Generated by Django 5.2.5 on 2025-08-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_remove_course_image_section_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="year",
            field=models.IntegerField(default=2025),
        ),
    ]
