# Generated by Django 5.2.5 on 2025-08-27 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_section_year"),
        ("users", "0006_alter_registrar_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="users.teacher",
            ),
        ),
    ]
