# Generated by Django 5.2.5 on 2025-08-30 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0008_alter_section_teacher"),
        ("departments", "0002_alter_department_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numbered_semester", models.PositiveIntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculums",
                        to="courses.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("BS", "Bachelor of Science (B.S.)"),
                            ("MS", "Master of Science (M.S.)"),
                            ("PhD", "Doctor of Philosophy (Ph.D.)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="programs",
                        through="curriculums.Curriculum",
                        to="courses.course",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "degree")},
            },
        ),
        migrations.AddField(
            model_name="curriculum",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="curriculums",
                to="curriculums.program",
            ),
        ),
    ]
