# Generated by Django 5.2.5 on 2025-09-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculums", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="degree",
            field=models.CharField(
                choices=[
                    ("BS", "Bachelor of Science"),
                    ("MS", "Master of Science"),
                    ("PhD", "Doctor of Philosophy"),
                ],
                max_length=10,
            ),
        ),
    ]
