# Generated by Django 5.2.5 on 2025-09-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_section_teacher"),
        ("curriculums", "0002_alter_program_degree"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="curriculum",
            unique_together={("program", "course")},
        ),
    ]
