# Generated by Django 5.2.5 on 2025-08-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
